version: "3"

services:
  db_alm:
    container_name: db_alm
    image: postgres:11
    restart: unless-stopped
    volumes:
      - db_alm-data:/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      TZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  db_alm-data:
