FROM node:18-alpine
WORKDIR /usr/app

COPY . .
RUN npm install && npm cache clean --force
ENV PATH=/usr/app/node_modules/.bin:$PATH

RUN apk add --no-cache tzdata
ENV TZ="America/Sao_Paulo"

WORKDIR /usr/app/dev
COPY tsconfig.json ./

COPY src ./src
COPY .env ./

COPY init.sh ./

ENTRYPOINT ["npm", "run", "start:watch"]